// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hgqiqarmkjhhguzvjvxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhncWlxYXJta2poaGd1enZqdnh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NTU4NDcsImV4cCI6MjA2NDUzMTg0N30.Vg_Nal3c3T-CJqJ251GXOiNrZPENH8yAGWB16GN1EbQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);